services:
  # <-- Kafka --> #
  zookeeper:
    image: confluentinc/cp-zookeeper
    profiles: [ kafka, all ]
    container_name: zookeeper
    ports:
      - "2181:2181"
    env_file:
      - .env

  kafka:
    image: confluentinc/cp-kafka
    profiles: [ kafka, all ] 
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    env_file:
      - .env
    # depends_on:
    #   - zookeeper
  # <-- End Kafka --> #

  # <-- Producers --> #
  shodan-asn-producer:
    image: python-runner
    profiles: [ not-kafka, all ]
    container_name: shodan_asn_producer
    build:
      context: ./
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /src
    environment:
      - SCRIPT=shodan_asn_producer
    env_file:
      - .env
    # depends_on:
    #   - kafka

  shodan-name-producer:
    image: python-runner
    profiles: [ not-kafka, all ]
    container_name: shodan_name_producer
    build:
      context: ./
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /src
    environment:
      - SCRIPT=shodan_name_producer
    env_file:
      - .env
    # depends_on:
    #   - kafka
  # <-- End Producers --> #

  # <-- Transformation --> #
  format-transformation:
    image: python-runner
    profiles: [ not-kafka, transform, all ]
    container_name: format-transformation
    build:
      context: ./
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /src
    environment:
      - SCRIPT=format-transformation
    env_file:
      - .env
    # depends_on:
    #   - kafka

  # crowdsec-enrich:
  #   image: python-runner
  #   profiles: [ not-kafka, transform, all ]
  #   container_name: crowdsec_enrich
  #   build:
  #     context: ./
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./src
  #         target: /src
  #   environment:
  #     - SCRIPT=crowdsec_enrich
  #   env_file:
  #     - .env
  #   depends_on:
  #     - kafka
  # mongodb-connector

  # flaskp-api-connector

  # dispatcher-connector

  # flask-display-connector

volumes: 
  crowdsec-config:
  crowdsec-db: