# Sample from https://github.com/conduktor/kafka-stack-docker-compose/blob/master/zk-single-kafka-single.yml

version: '2.1'
services:
  zoo:
    image: confluentinc/cp-zookeeper:7.4.4
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    env_file:
      - .env

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    env_file:
      - .env
    depends_on:
      - zoo1