services:
  shodan_producer:
    profiles: [ not-kafka, producer, all ]
    build: 
      context: .
      dockerfile: pythonDockerfile
    container_name: shodan_producer
    env_file:
      - .env
      
  shodan_display: 
    profiles: [ all, display ]
    container_name: shodan_display
    restart: always
    build:
      context: .
      dockerfile: expressDockerfile
    env_file:
      - .env
    networks:
      - proxy

networks: 
  default:
  proxy: 
    name: proxy
    external: true