version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    env_file:
      - .env

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    env_file:
      - .env
    depends_on:
      - zookeeper

  # shodan-producer
  shodan-producer:
    image: python-runner
    build:
      context: ./
    environment:
      - SCRIPT=shodan-producer
    env_file:
      - .env
    depends_on:
      - kafka


  # airflow-transformation

  # crowdsec-enrich
  crowdsec-enrich:
    image: python-runner
    build:
      context: ./
    environment:
      - SCRIPT=crowdsec-enrich
    env_file:
      - .env
    depends_on:
      - kafka

  # crowdsec-lapi-enrich

  # mongodb-connector

  # flaskp-api-connector

  # dispatcher-connector

  # flask-display-connector

